version = 0.1
[default.deploy.parameters]
stack_name = "abyssal-infinity-ws-deployment"
resolve_s3 = true
s3_prefix = "abyssal-infinity-ws-deployment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
